# Generated by Django 4.1.4 on 2023-01-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_variatns_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variatns',
            old_name='product',
            new_name='product_variant',
        ),
    ]
