# Generated by Django 4.1.4 on 2023-02-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_variatns_update_alter_product_update_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
