# Generated by Django 4.1.4 on 2023-02-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_product_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='variatns',
            name='change',
            field=models.BooleanField(default=False),
        ),
    ]
