# Generated by Django 4.1.4 on 2023-02-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_coupon_end_alter_coupon_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
